# Basic
title: 郑兆龙
subtitle: 个人博客
description: 欢迎来到我的个人博客~
# 头像里面的标题
avatarTitle: zzl
# 头像里面的描述
avatarDesc: 前端
url: "https://zhaolong06.github.io"

# Comment
comment:
    disqus: blog-cturjncndo
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: 2138537183 
    github: zhaolong06
    # twitter: 
    mail: zhaolong0206@gmail.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: feca793ecc711aa6bd28c3eef1880627  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-111594972-1   
    host: auto

permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


